version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      LANG: C.UTF-8
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf ##配置文件位置映射
      - ./html:/usr/share/nginx/html     ##网页文件位置映射
    depends_on:
      - php
  php:
    image: bitnami/php-fpm
    environment:
      LANG: C.UTF-8
    volumes:
      - .:/app ##网页文件位置映射
    depends_on:
      - mysql
    links: 
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bighu
      MYSQL_PASSWORD: mydata ##数据库用户密码
      MYSQL_DATABASE: data
    ports: 
      - 3306:3306
    volumes:
      - ./shiyan2.sql:/docker-entrypoint-initdb.d/db.sql
